/*
 *  lessons.c - the lessons for Dvorak 7min
 *  Copyright (C) 1998-2001  Ragnar Hojland Espinosa
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include "lessons.h"

/* name of the lesson, text of the lesson.. you can embed \n's except on
 * the last line.
 *
 *   lesson name should be shorter than 37
 *   lesson text should 6 lines or less, with an end of page marker (\x01)
 *
 * note that as of version 1.Makefile using ASCII files is possible too.
 */

char *lessons[] =
{

"move your fingers",
"\x2"
"iek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.\n"
"rtgcrtmwrtgcrtmwrtgcrtmwrtgcrtmwrtgcrtmwrtgc\n"
"eik.iehjiek.iehjiek.iehjik.iehjiek.iehjiek.ieheiek.iehjiek.iehjiek.iehjiek.iek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.iehjiek.\n"
"rtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcmwrtgcrtgcrtgcrtmwrtgcrtgcrtgcrtgcrtgcrtmwrtgcrtmwrtgcrtgcrtmwrtgcrtmwrtgcrtgcrtmwrtgcrtgcrtmwrtgcrtmwrtgcrtmwrtgcrtmwrtgcrtgcrtmwrtgcrtgcrtmwrtgcrtgcrtgcrtgcrtmwrtgcrtgcrtgcrtgcrtmwmtgcrtgcrtgcrtgcrtmwrtgcrtgcrtwmrtgcrtwmrtmwrtgcrtmwrtgccrtmwrtgcrtmwrtgcrtmwrtrtgcrtmwrtgcmtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtgcrtmwrtrtrtrtrtrtmwmwwmwmw\n"
"mw\n",

"most common words (3 times)",
"\x2"
"the the the\n"
"of of of\n"
"and and and\n"
"to to to\n"
"in in in\n"
"a a a\n"
"is is is\n"
"that that that\n"
"for for for\n"
"it it it\n"
"as as as\n"
"was was was\n"
"with with with\n"
"be be be\n"
"by by by\n"
"on on on\n"
"not not not\n"
"he he he\n"
"i i i\n"
"this this this\n"
"are are are\n"
"or or or\n"
"his his his\n"
"from from from from\n"
"\x1"
"at at at\n"
"which which which\n"
"but but but\n"
"have have have\n"
"an an an\n"
"had had had\n"
"they they they\n"
"you you you\n"
"were were were\n"
"their their their\n"
"one one one\n"
"all all all\n"
"we we we\n"
"can can can\n"
"her her her\n"
"has has has\n"
"there there there\n"
"been been been\n"
"if if if\n"
"more more more\n"
"when when when when\n"
"will will will\n"
"would would would\n"
"who who who\n"
"no no no\n",

"most common words (6 times)",
"\x2"
"the the the the the the\n"
"of of of of of of\n"
"and and and and and and\n"
"to to to to to to\n"
"in in in in in in\n"
"a a a a a a\n"
"is is is is is is\n"
"that that that that that that\n"
"for for for for for for\n"
"it it it it it it\n"
"as as as as as as\n"
"was was was was was was\n"
"with with with with with with\n"
"be be be be be be\n"
"by by by by by by\n"
"on on on on on on\n"
"not not not not not not\n"
"he he he he he he\n"
"i i i i i i\n"
"this this this this this this\n"
"are are are are are are\n"
"or or or or or or\n"
"his his his his his his\n"
"from from from from from from\n"
"at at at at at at\n"
"which which which which which which\n"
"but but but but but but\n"
"\x1"
"have have have have have have\n"
"an an an an an an\n"
"had had had had had had\n"
"they they they they they they\n"
"you you you you you you\n"
"were were were were were were\n"
"their their their their their their\n"
"one one one one one one\n"
"all all all all all all\n"
"we we we we we we\n"
"can can can can can can\n"
"her her her her her her\n"
"has has has has has has\n"
"there there there there there there\n"
"been been been been been been\n"
"if if if if if if\n"
"more more more more more more\n"
"when when when when when when when when\n"
"will will will will will will\n"
"would would would would would would\n"
"who who who who who who\n"
"so so so so so so\n"
"no no no no no no\n",

"bigrams",
"\x2"
"th th th th th th\n"
"he he he he he he\n"
"in in in in in in\n"
"er er er er er er\n"
"an an an an an an\n"
"re re re re re re\n"
"on on on on on on\n"
"at at at at at at\n"
"en en en en en en\n"
"nd nd nd nd nd nd\n"
"ti ti ti ti ti ti\n"
"es es es es es es\n"
"or or or or or or\n"
"te te te te te te\n"
"of of of of of of\n"
"ed ed ed ed ed ed\n"
"is is is is is is\n"
"it it it it it it\n"
"al al al al al al\n"
"ar ar ar ar ar ar\n"
"st st st st st st\n"
"to to to to to to\n"
"nt nt nt nt nt nt\n"
"ng ng ng ng ng ng\n"
"se se se se se se\n"
"ha ha ha ha ha ha\n"
"as as as as as as\n"
"\x1"
"ou ou ou ou ou ou\n"
"io io io io io io\n"
"le le le le le le\n"
"ve ve ve ve ve ve\n"
"co co co co co co\n"
"me me me me me me\n"
"de de de de de de\n"
"hi hi hi hi hi hi\n"
"ri ri ri ri ri ri\n"
"ro ro ro ro ro ro\n"
"ic ic ic ic ic ic\n"
"ne ne ne ne ne ne\n"
"ea ea ea ea ea ea\n"
"ra ra ra ra ra ra\n"
"ce ce ce ce ce ce\n"
"li li li li li li\n"
"ch ch ch ch ch ch\n"
"ll ll ll ll ll ll\n"
"be be be be be be\n"
"ma ma ma ma ma ma\n"
"si si si si si si\n"
"om om om om om om\n"
"ur ur ur ur ur ur\n",

"trigrams",
"\x2"
"the the the the the the\n"
"and and and and and and\n"
"ing ing ing ing ing ing\n"
"ent ent ent ent ent ent\n"
"for for for for for for\n"
"her her her her her her\n"
"ter ter ter ter ter ter\n"
"hat hat hat hat hat hat\n"
"ere ere ere ere ere ere\n"
"ate ate ate ate ate ate\n"
"his his his his his his\n"
"con con con con con con\n"
"res res res res res res\n"
"ver ver ver ver ver ver\n"
"all all all all all all\n"
"ons ons ons ons ons ons\n"
"nce nce nce nce nce nce\n"
"men men men men men men\n"
"ith ith ith ith ith ith\n"
"ted ted ted ted ted ted\n"
"ers ers ers ers ers ers\n"
"pro pro pro pro pro pro\n"
"wit wit wit wit wit wit\n"
"are are are are are are\n"
"ess ess ess ess ess ess\n"
"not not not not not not\n"
"ive ive ive ive ive ive\n"
"\x1"
"was was was was was was\n"
"ect ect ect ect ect ect\n"
"rea rea rea rea rea rea\n"
"com com com com com com\n"
"eve eve eve eve eve eve\n"
"per per per per per per\n"
"int int int int int int\n"
"est est est est est est\n"
"sta sta sta sta sta sta\n"
"ist ist ist ist ist ist\n"
"ear ear ear ear ear ear\n"
"one one one one one one\n"
"our our our our our our\n"
"rat rat rat rat rat rat\n",

"4 grams",
"\x2"
"tion tion tion tion tion tion\n"
"that that that that that that\n"
"ther ther ther ther ther ther\n"
"with with with with with with\n"
"ment ment ment ment ment ment\n"
"this this this this this this\n"
"here here here here here here\n"
"from from from from from from\n"
"ould ould ould ould ould ould\n"
"ting ting ting ting ting ting\n"
"ence ence ence ence ence ence\n"
"have have have have have have\n"
"ight ight ight ight ight ight\n"
"sion sion sion sion sion sion\n"
"ever ever ever ever ever ever\n"
"ical ical ical ical ical ical\n"
"they they they they they they\n"
"ough ough ough ough ough ough\n"
"ance ance ance ance ance ance\n"
"were were were were were were\n"
"tive tive tive tive tive tive\n"
"over over over over over over\n"
"ding ding ding ding ding ding\n"
"pres pres pres pres pres pres\n"
"nter nter nter nter nter nter\n"
"comp comp comp comp comp comp\n"
"able able able able able able\n"
"\x1"
"heir heir heir heir heir heir\n"
"thei thei thei thei thei thei\n"
"ring ring ring ring ring ring\n"
"ture ture ture ture ture ture\n"
"cont cont cont cont cont cont\n"
"ents ents ents ents ents ents\n"
"cons cons cons cons cons cons\n"
"thin thin thin thin thin thin\n"
"part part part part part part\n"
"form form form form form form\n"
"ning ning ning ning ning ning\n"
"some some some some some some\n",

"5 grams",
"\x2"
"tions tions tions tions tions tions\n"
"which which which which which which\n"
"ction ction ction ction ction ction\n"
"other other other other other other\n"
"their their their their their their\n"
"there there there there there there\n"
"ition ition ition ition ition ition\n"
"ement ement ement ement ement ement\n"
"inter inter inter inter inter inter\n"
"ratio ratio ratio ratio ratio ratio\n"
"would would would would would would\n"
"these these these these these these\n"
"state state state state state state\n"
"thing thing thing thing thing thing\n"
"under under under under under under\n"
"ssion ssion ssion ssion ssion ssion\n"
"ectio ectio ectio ectio ectio ectio\n"
"catio catio catio catio catio catio\n"
"latio latio latio latio latio latio\n"
"about about about about about about\n"
"count count count count count count\n"
"ments ments ments ments ments ments\n"
"rough rough rough rough rough rough\n"
"prese prese prese prese prese prese\n"
"ative ative ative ative ative ative\n"
"hough hough hough hough hough hough\n"
"press press press press press press\n"
"\x1"
"first first first first first first\n"
"after after after after after after\n"
"cause cause cause cause cause cause\n"
"where where where where where where\n"
"could could could could could could\n"
"great great great great great great\n",

"6 grams",
"\x2"
"ations ations ations ations ations ations\n"
"ration ration ration ration ration ration\n"
"tional tional tional tional tional tional\n"
"nation nation nation nation nation nation\n"
"ection ection ection ection ection ection\n"
"cation cation cation cation cation cation\n"
"lation lation lation lation lation lation\n"
"though though though though though though\n"
"presen presen presen presen presen presen\n"
"tation tation tation tation tation tation\n"
"should should should should should should\n"
"resent resent resent resent resent resent\n"
"dition dition dition dition dition dition\n"
"differ differ differ differ differ differ\n"
"people people people people people people\n"
"struct struct struct struct struct struct\n"
"system system system system system system\n"
"before before before before before before\n"
"change change change change change change\n"
"follow follow follow follow follow follow\n",

"common words again",
"\x2"
"the the the the the the\n"
"of of of of of of\n"
"and and and and and and\n"
"to to to to to to\n"
"in in in in in in\n"
"a a a a a a\n"
"is is is is is is\n"
"that that that that that that\n"
"be be be be be be\n"
"it it it it it it\n"
"by by by by by by\n"
"are are are are are are\n"
"for for for for for for\n"
"was was was was was was\n"
"as as as as as as\n"
"he he he he he he\n"
"with with with with with with\n"
"on on on on on on\n"
"his his his his his his\n"
"at at at at at at\n"
"which which which which which which\n"
"but but but but but but\n"
"from from from from from from\n"
"has has has has has has\n"
"this this this this this this\n"
"will will will will will will\n"
"one one one one one one\n"
"\x1"
"have have have have have have\n"
"not not not not not not\n"
"were were were were were were\n"
"or or or or or or\n"
"all all all all all all\n"
"their their their their their their\n"
"an an an an an an\n"
"I I I I I I\n"
"there there there there there there\n"
"been been been been been been\n"
"many many many many many many\n"
"more more more more more more\n"
"so so so so so so\n"
"when when when when when when\n"
"had had had had had had\n"
"may may may may may may\n"
"today today today today today today\n"
"who who who who who who\n"
"would would would would would would\n"
"time time time time time time\n"
"we we we we we we\n"
"about about about about about about\n"
"after after after after after after\n"
"dollars dollars dollars dollars dollars dollars\n"
"if if if if if if\n"
"my my my my my my\n"
"other other other other other other\n"
"\x1"
"some some some some some some\n"
"them them them them them them\n"
"being being being being being being\n"
"its its its its its its\n"
"no no no no no no\n"
"only only only only only only\n"
"over over over over over over\n"
"very very very very very very\n"
"you you you you you you\n"
"into into into into into into\n"
"most most most most most most\n"
"than than than than than than\n"
"they they they they they they\n"
"day day day day day day\n"
"even even even even even even\n"
"made made made made made made\n"
"out out out out out out\n"
"first first first first first first\n"
"great great great great great great\n"
"must must must must must must\n"
"these these these these these these\n"
"can can can can can can\n"
"days days days days days days\n"
"every every every every every every\n"
"found found found found found found\n"
"general general general general general general\n"
"\x1"
"her her her her her her\n"
"here here here here here here\n"
"last last last last last last\n"
"new new new new new new\n"
"now now now now now now\n"
"people people people people people people\n"
"public public public public public public\n"
"said said said said said said\n"
"since since since since since since\n"
"still still still still still still\n"
"such such such such such such\n"
"through through through through through through\n"
"under under under under under under\n"
"up up up up up up\n"
"war war war war war war\n"
"well well well well well well\n"
"where where where where where where\n"
"while while while while while while\n"
"years years years years years years\n"
"before before before before before before\n"
"between between between between between between\n"
"country country country country country country\n"
"debts debts debts debts debts debts\n"
"good good good good good good\n"
"him him him him him him\n"
"interest interest interest interest interest interest\n"
"large large large large large large\n"
"like like like like like like\n"
"make make make make make make\n"
"our our our our our our\n"
"take take take take take take\n"
"upon upon upon upon upon upon\n"
"whatab whatab whatab whatab whatab whatab\n",

"hard words",
"\x2"
"the the the the the the\n"
"th th th th th th\n"
"han han han han han han\n"
"ha ha ha ha ha ha\n"
"hry hry hry hry hry hry\n"
"hr hr hr hr hr hr\n"
"lep lep lep lep lep lep lep lep\n"
"le le le le le le\n"
"him hio hio him hio hio\n"
"hi hi hi hi hi hi\n"
"nea nea nea nea nea nea\n"
"ne ne ne ne ne ne\n"
"chu chu chu chu chu chu\n"
"ch ch ch ch ch ch\n"
"urd urd urd urd urd urd\n"
"ur ur ur ur ur ur\n"
"ndr ndr ndr ndr ndr ndr\n"
"nd nd nd nd nd nd\n"
"ntr ntr ntr ntr ntr ntr\n"
"nt nt nt nt nt nt\n"
"ngs ngs ngs ngs ngs ngs\n"
"ng ng ng ng ng ng\n"
"lap lap lap lap lap lap\n"
"ap ap ap ap ap ap\n"
"lop lop lop lop lop lop\n"
"op op op op op op\n"
"rep rep rep rep rep rep\n"
"ep ep ep ep ep ep\n"
"rip rip rip rip rip rip\n"
"ip ip ip ip ip ip\n"
"tup tup tup tup tup tup\n"
"up up up up up up\n"
"tpa tpa tpa tpa tpa tpa\n"
"pa pa pa pa pa pa\n"
"tpo tpo tpo tpo tpo tpo\n"
"po po po po po po\n"
"lpe lpe lpe lpe lpe lpe\n"
"pe pe pe pe pe pe\n"
"lpi lpi lpi lpi lpi lpi\n"
"pi pi pi pi pi pi\n"
"lpu lpu lpu lpu lpu lpu\n"
"pu pu pu pu pu pu\n"
"heye heye heye heye heye heye\n"
"hey hey hey hey hey hey\n"
"anoa anoa anoa anoa anoa anoa\n"
"ano ano ano ano ano ano\n"
"allt allt allt allt allt allt\n"
"all all all all all all\n"
"ings ings ings ings ings ings\n"
"ing ing ing ing ing ing\n"
"fort fort fort fort fort fort\n"
"for for for for for for\n"
"hery hery hery hery hery hery\n"
"her her her her her her\n"
"eren eren eren eren eren eren\n"
"ere ere ere ere ere ere\n"
"ate ate ate ate ate ate\n"
"ano ano ano ano ano ano\n"
"his his his his his his\n"
"ons ons ons ons ons ons\n"
"nce nce nce nce nce nce\n"
"nts nts nts nts nts nts\n"
"ith ith ith ith ith ith\n"
"ess ess ess ess ess ess\n"
"not not not not not not\n"
"ive ive iev ive ive iev\n"
"per per per per per per\n"
"int int int int int int\n"
"ins ins ins ins ins ins\n"
"thr thr thr thr thr thr\n"
"you you you you you you\n"
"spe spe spe spe spe spe\n"
"ope ope ope ope ope ope\n",

"most hard",
"\x2"
"will will will will will will\n"
"ture ture ture ture ture ture\n"
"ther ther ther ther ther ther\n"
"with with with with with with\n"
"this this this this this this\n"
"here here here here here here\n"
"have have have have have have\n"
"from from from from from from\n"
"form form form form form form\n"
"ight ight ight ight ight ight\n"
"ical ical ical ical ical ical\n"
"heir heir heir heir heir heir\n"
"they they they they they they\n"
"ture ture ture ture ture ture\n"
"true true true true true true\n"
"ents ents ents ents ents ents\n"
"nece nece nece nece nece nece\n"
"nter nter nter nter nter nter\n"
"ents ents ents ents ents ents\n"
"arti arti arti arti arti arti\n"
"cult cult cult cult cult cult\n"
"sent sent sent sent sent sent\n"
"rica rica rica rica rica rica\n"
"arti arti arti arti arti arti\n"
"ever ever ever ever ever ever\n"
"cula cula cula cula cula cula\n"
"know know know know know know\n"
"\x1"
"they they they they they they\n"
"which which which which which which\n"
"there there there there there there\n"
"their their their their their their\n"
"inter inter inter inter inter inter\n"
"under under under under under under\n"
"about about about about about about\n"
"rough rough rough rough rough rough\n"
"hough hough hough hough hough hough\n"
"first first first first first first\n"
"where where where where where where\n"
"tions tions tions tions tions tions\n"
"ments ments ments ments ments ments\n"
"though though though though though though\n"
"system system system system system system\n"
"before before before before before before\n"
"follow follow follow follow follow follow\n"
"between between between between between between\n"
"because because because because because because\n"
"develop devolop devolop develop devolop devolop\n"
"america america america america america america\n"
"without without without without without without\n"
"another another another another another another\n"
"special special special special special special\n",
/* end of lessons. do not remove these zeroes */
0, 0
};

